using Microsoft.Exchange.WebServices.Data;
using System;
using System.Collections.Generic;
using System.IO;
using System.Threading;

namespace ExchangeChangeGenerator
{
    class ExchangeGenerator
    {
        public string serverIP;
        string[] credentials;
        int amountToGenerate, generateTime, messageSize;    
        public ExchangeGenerator(string serverIP, string[] credentials, int amountToGenerate, int generateTime, int messageSize)
        {
            this.serverIP = serverIP;
            this.credentials = credentials;
            this.amountToGenerate = amountToGenerate;
            this.generateTime = generateTime;
            this.messageSize = messageSize;
        }

        private void sendMessages(ExchangeService service)
        {
            int messagesToSent = amountToGenerate / messageSize;

            Logger.Log("Start message generation.", LogLevel.Info, serverIP);
            Logger.Log(messagesToSent.ToString() + " messages will be sent.", LogLevel.Info, serverIP);

            for (int i = 0; i < messagesToSent; i++)
            {
                createRandomFile(this.messageSize);
                EmailMessage email = new EmailMessage(service);

                email.ToRecipients.Add(this.credentials[0]);
                email.Subject = "Exchange Change Generator";
                email.Body = new MessageBody("This is email generated by Exchange Change Generator");
                email.Attachments.AddFileAttachment(serverIP.ToString()+"\\attachment.dat");
                email.Send();
                Logger.Log("Sending E-mail Message #" + (i + 1).ToString(), LogLevel.Info, serverIP);
            }
        }

        private void deleteMessages(ExchangeService service)
        {
            Logger.Log("Cleanup Inbox and Draft folders", LogLevel.Info, serverIP);

            List<Folder> folderCollection = new List<Folder>();

            folderCollection.Add(Folder.Bind(service, WellKnownFolderName.Inbox));
            folderCollection.Add(Folder.Bind(service, WellKnownFolderName.Drafts));

            foreach (var folder in folderCollection)
            {
                folder.Empty(DeleteMode.HardDelete, true);
            }         
        }
        public void startGenerator()
        {
            try
            {
                ExchangeService service = new ExchangeService(ExchangeVersion.Exchange2010_SP1);
                service.Credentials = new WebCredentials(this.credentials[0], this.credentials[1]);
                service.Url = new Uri("https://" + this.serverIP + "/EWS/Exchange.asmx");
                service.Timeout = 300000;
                try
                {
                    service.FindFolders(WellKnownFolderName.Inbox, new FolderView(1));
                }

                catch (ServiceResponseException e)
                {
                    clearMailQueue();
                }

                catch (Exception e)
                {
                    Console.WriteLine("Sorry, the server {0} is unreachable, please see logs", serverIP);
                    Logger.Log("Sorry, the server is unreachable with error: " + e.Message + ". Stack Trace: " + e.StackTrace, LogLevel.Error, serverIP);
                    return;
                }


                Console.WriteLine("Connection to server {0} successfully established", this.serverIP);
                Logger.Log("Connection to server successfully established", LogLevel.Info, serverIP);

                while (true)
                {
                    try
                    {
                        DateTime startTime = DateTime.Now;
                        DateTime nextCycleTime = startTime.AddMinutes(this.generateTime);

                        sendMessages(service);

                        TimeSpan sleepTime = nextCycleTime - DateTime.Now;
                        if (sleepTime.TotalMilliseconds >= 0)
                        {
                            Logger.Log("Waiting " + sleepTime.Minutes.ToString() + " minutes to start next cycle.", LogLevel.Info, serverIP);
                            Thread.Sleep(sleepTime);
                        }
                    }
                    catch (ServiceResponseException)
                    {
                        deleteMessages(service);
                    }
                    catch (CreateAttachmentException)
                    {
                        clearMailQueue();
                    }
                    
                }
            }
            catch (Exception e)
            {
                Console.WriteLine("Something wrong with server {0}, please see logs", serverIP);
                Logger.Log(e.Message + ". Stack Trace: " + e.StackTrace, LogLevel.Error, serverIP);
                return;
            }
        }

        private void createRandomFile(int sizeInMb)
        {
            byte[] data = new byte[sizeInMb * 1024 * 1024];
            Random random = new Random();
            random.NextBytes(data);
            Directory.CreateDirectory(serverIP.ToString());
            File.WriteAllBytes(serverIP.ToString()+"\\attachment.dat", data);
        }

        private void clearMailQueue()
        {
            Logger.Log("CreateAttachemtException caught. Trying to delete mail.que file to free disk space.", LogLevel.Warning, serverIP);
            PowerShellConnector powershellConnector = new PowerShellConnector(serverIP, credentials[0], credentials[1]);
            WMIConnector wmiConnector = new WMIConnector(serverIP, credentials[0], credentials[1]);
            wmiConnector.StopExchangeService();
            powershellConnector.PerformCommandInRunspace(powershellConnector.DeleteAndRecreateMailQue, PSInstanceToConnect.Default);
            wmiConnector.StartExchangeService();
            powershellConnector.PerformCommandInRunspace(powershellConnector.MountMailbox, PSInstanceToConnect.Exchange);
        }
    }
}
